rest-api-basics: Develop api for gift certificates system
m-hromov/learning pull request #3
Opened 2023-04-02 14:12 UTC by m-hromov

I don't have enough time, so some integration test's asserts are missing.

2023-04-04 08:05 UTC, SviatoslavSlichnyi commented
build-tools-git-task this folder is useless here. Please, create a new folder structure:

- Module-01
  - build-task
  - git-task
- Module-02
  - api
  - boot
  - common
  - repository
  - service
  - pom.xml

You need to separate homeworks. Right now, it is mixed up. Please, change folder structure.

2023-04-04 08:06 UTC, SviatoslavSlichnyi commented
Please, provide steps to run your application in README.md file or provide IntelliJ IDEA run files. Newcomers should know how your project can be executed for testing.

2023-04-04 08:15 UTC, SviatoslavSlichnyi commented
It is not required, but it will good if you create two profiles: dev and prod.

- dev profile will be used with h2 database.
- prod profile will be used with postgresql database.

2023-04-04 09:02 UTC, SviatoslavSlichnyi approved these changes

2023-04-04 09:02 UTC, SviatoslavSlichnyi commented on service/src/main/java/com/epam/esm/service/impl/GiftCertificateServiceImpl.java
> +        } catch (Exception e) {
patch should update those fields which come as request and are not NULL

2023-04-04 09:02 UTC, SviatoslavSlichnyi commented on service/src/main/java/com/epam/esm/service/impl/GiftCertificateServiceImpl.java
> +        } catch (Exception e) {
Please, refactor it

2023-04-04 09:04 UTC, SviatoslavSlichnyi requested changes
Found some issues

2023-04-04 20:39 UTC, m-hromov commented on service/src/main/java/com/epam/esm/service/impl/GiftCertificateServiceImpl.java
> +        } catch (Exception e) {
Please, take a look on PatchUtil. It checks whether the field is null or not:
https://github.com/m-hromov/learning/pull/3/files#diff-51d865a6f0387d770776b0a353890fe1f05ce088aaa2545ddc31f257460def60R13

2023-04-14 09:24 UTC, SviatoslavSlichnyi requested changes

2023-04-14 09:24 UTC, SviatoslavSlichnyi commented on Module-02/api/src/main/java/com/epam/esm/api/GiftController.java
> +                .toList();
It will be better to move to Service Layer

2023-04-14 09:24 UTC, SviatoslavSlichnyi commented on Module-02/api/src/main/java/com/epam/esm/api/GiftController.java
> +    @GetMapping(GET_BY_ID)
I don't recommend to use const fields here, it will take more time to find api. String can be specified in annotation. It will not have any influence on application performance

2023-04-14 09:24 UTC, SviatoslavSlichnyi commented on Module-02/api/src/main/java/com/epam/esm/api/GiftController.java
> +    public GiftCertificateDto findById(@PathVariable("id") Long id) {
`@PathVariable("id")` is can be simplified to `@PathVariable`. If path variable name is the same as parameter name.

2023-04-14 09:24 UTC, SviatoslavSlichnyi commented on Module-02/api/src/main/java/com/epam/esm/api/TagController.java
> +    public static final String TAGS_BASE = "/tags";
the same as in GiftController

2023-04-14 09:24 UTC, SviatoslavSlichnyi commented on Module-02/common/src/main/java/com/epam/esm/model/GiftCertificate.java
> +    private List<Tag> tags;
it is better to exclude collection from toString(), equals() and hashcode() methods.

Try @ToString.Exclude annotation

2023-04-14 09:24 UTC, SviatoslavSlichnyi commented on service/src/main/java/com/epam/esm/service/impl/GiftCertificateServiceImpl.java
> +        } catch (Exception e) {
perfect

2023-04-30 14:59 UTC, merged