Module-03/rest-api-advanced
m-hromov/learning pull request #8
Opened 2023-05-02 19:58 UTC by m-hromov

2023-05-05 16:31 UTC, SviatoslavSlichnyi requested changes

2023-05-05 16:31 UTC, SviatoslavSlichnyi commented on Module-03/boot/src/main/java/com/epam/esm/boot/config/HibernateConfig.java
> +        properties.put("hibernate.hbm2ddl.auto", "update");
hibernate.dialect and hibernate.hbm2ddl.auto - take values from properties file

2023-05-05 16:31 UTC, SviatoslavSlichnyi commented on Module-03/boot/src/main/resources/application.yml
> +    driver-class-name: org.postgresql.Driver
it would be better to use here h2 db configs in order to start app with default configs and work with app

2023-05-05 16:31 UTC, SviatoslavSlichnyi commented on Module-03/common/src/main/java/com/epam/esm/dto/OrderInfoDto.java
> +    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "MM-dd-yyyy HH:mm:ss")
if I am not wrong it is configured in ObjectMapperConfig

2023-05-05 16:31 UTC, SviatoslavSlichnyi commented on Module-03/common/src/main/java/com/epam/esm/model/User.java
> +    private List<Order> orders;
It is better to exclude collections from quals()-hashcode() and toString method.

2023-05-05 17:04 UTC, SviatoslavSlichnyi commented
Please, edit Run/Debug configuration. Tomcat is actual now

2023-05-05 17:07 UTC, SviatoslavSlichnyi requested changes

2023-05-05 17:07 UTC, SviatoslavSlichnyi commented on Module-03/api/src/main/java/com/epam/esm/api/TagController.java
> +        return tagService.findMostWidelyUsedTagOfUserWithHighestOrderCost();
Perfect! You showed your strong knowledge and understanding of SQL querying.

2023-05-05 17:12 UTC, SviatoslavSlichnyi commented
Everything is really-really good. Quality of your code is high. 
My comments are not very strict, but I shared with you with best practices which I knew from production experience.

2023-05-05 17:15 UTC, SviatoslavSlichnyi commented
Also I didn't found implemented the following requirements:
- Make an order on gift certificate for a user (user should have an ability to buy a certificate).
I didn't find a way to create an order.

- Support HATEOAS on REST endpoints.
it is not implemented.

- Search for gift certificates by several tags (“and” condition).
it is not implemented.

- Pagination should be implemented for all GET endpoints. Please, create a flexible and non-erroneous solution. Handle all exceptional cases.
Please, write unite and integration tests in order to prove that your logic is tested from different angles.

2023-05-09 20:19 UTC, m-hromov commented on Module-03/api/src/main/java/com/epam/esm/api/UserController.java
> +    public ResponseEntity<OrderDto> findAllUserOrders(@PathVariable Long userId,
It should've been an endpoint for order creation. Just a typo in method's name

2023-05-09 20:21 UTC, m-hromov commented on Module-03/api/src/main/java/com/epam/esm/api/UserController.java
> +    public ResponseEntity<UserLoginResponseDto> login(@RequestBody UserLoginRequestDto requestDto) {
It's not implemented yet anyway)

2023-05-09 21:08 UTC, m-hromov commented on Module-03/common/src/main/java/com/epam/esm/dto/OrderInfoDto.java
> +    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "MM-dd-yyyy HH:mm:ss")
Yes, but it writes dates as timestamps for some reason without JsonFormat anyway

2023-05-29 04:03 UTC, SviatoslavSlichnyi commented
Support HATEOAS on REST endpoints. it is not implemented. - is not implemented on all end points

2023-05-29 04:03 UTC, SviatoslavSlichnyi commented
More unit and interrogation tests are needed

2023-05-31 17:37 UTC, SviatoslavSlichnyi commented
Business requirements:
[+] Change single field of gift certificate (e.g. implement the possibility to change only duration of a certificate or only price).
[+] Add new entity User.
[+] implement only get operations for user entity.
[+] Make an order on gift certificate for a user (user should have an ability to buy a certificate).
[+] Get information about user’s orders.
[+] Get information about user’s order: cost and timestamp of a purchase.
[+] The order cost should not be changed if the price of the gift certificate is changed.
[+] Get the most widely used tag of a user with the highest cost of all orders.
[+] Create separate endpoint for this query.
[+] Demonstrate SQL execution plan for this query (explain).
[+] Search for gift certificates by several tags (“and” condition).
[+] Pagination should be implemented for all GET endpoints. Please, create a flexible and non-erroneous solution. Handle all exceptional cases.
[+] Support HATEOAS on REST endpoints.

Application requirements
[+] JDK version: 8. Use Streams, java.time.*, an etc. where it is appropriate. (the JDK version can be increased in agreement with the mentor/group coordinator/run coordinator)
[+] Application packages root: com.epam.esm.
[+] Java Code Convention is mandatory (exception: margin size –120 characters).
[+] Apache Maven/Gradle, latest version. Multi-module project.
[+] Spring Framework, the latest version.
[+] Database: PostgreSQL/MySQL, latest version.
[+] Testing: JUnit, the latest version, Mockito.
[-] Service layer should be covered with unit tests not less than 80%. - coverage is 70%
[+] Hibernate should be used as a JPA implementation for data access. 
[+] Spring Transaction should be used in all necessary areas of the application.
[+] Audit data should be populated using JPA features (an example can be found in materials).

2023-05-31 18:03 UTC, SviatoslavSlichnyi approved these changes

2023-05-31 18:03 UTC, SviatoslavSlichnyi commented on Module-03/api/src/main/java/com/epam/esm/api/GiftController.java
> +    public ResponseEntity<GiftCertificateDto> create(@RequestBody GiftCertificate certificate) {
There is no validation in GiftCertificate. 
When name = null was passed then INTERNAL_SERVER_ERROR was thrown. It is not acceptable to return to user INTERNAL_SERVER_ERROR. each required data should be validated and if something is missed then appropriate message must be returned

2023-05-31 18:06 UTC, SviatoslavSlichnyi commented
The pull request was approved. 
Those comments were added just for your information about what else can be improved. 
I am sure you can handle it without any doubts, but let's not stack on this topic too mush and move on to other exciting things!

2023-06-01 07:22 UTC, SviatoslavSlichnyi approved these changes

2023-06-01 20:13 UTC, merged